//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor_Reg_2024_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Skor_SQL_2024_REG_2Entities : DbContext
    {
        public Skor_SQL_2024_REG_2Entities()
            : base("name=Skor_SQL_2024_REG_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnoz> Diagnoz { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Gospital> Gospital { get; set; }
        public virtual DbSet<Meropriation> Meropriation { get; set; }
        public virtual DbSet<Otdel> Otdel { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
        public virtual DbSet<Yslovie> Yslovie { get; set; }
    }
}
